name = "pico_twitter"
description = ""
version = "0.1.0-dev"

authors = ["Rolf Ebert"]
maintainers = ["Rolf Ebert <rolf.ebert.gcc@gmx.de>"]
maintainers-logins = ["RREE"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
website = ""
tags = []

[[depends-on]]
pico_bsp = "^2.0.0"
